
# Language/versions
language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.10"

# Build only master, version tags, and pull-requests
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - make ci

# Send notifications to the FEDs slack channel
notifications:
  slack: thefeds:vG3hLYB07EwTYpQFp3TNUx82
